### ISSUE TITLE
prefix 'arista_' is missing on custom fields

### ISSUE THREAD

**Issue by etiennelatulippe** [nautobot/nautobot-plugin-ssot-arista-cloudvision#114] opened 2022-10-27 17:28 UTC
### Environment
* Python version:  3.8
* Nautobot version:  1.4.7
* aristacv-sync version:  1.4.0

### Expected Behavior
I'm expecting to get custom fields from migration that include the prefix "arista_" in the slug.

### Observed Behavior
Custom fields are created, but without the prefix arista_.
Got a KeyError 'arista_eos' on sync from cloudvision to nautobot
Got a warning icon next to the slug column items saying : 'Name "all fields" does not match slug'

### Steps to Reproduce
From a fresh db.
1. nautobot-server -c nautobot_config.py migrate
2. Go to custom fields sub section from the Extensibility section

**Comment by jdrew82** [comment] 2022-10-28 13:43
I think I've figured out the problem. It appears that if you don't specify the slug on a CustomField that it uses the label field to fill it in. Because the label is passed and doesn't have the `arista_` prefix it causes this error. If we just specify the slug during the creation the issue is fixed. I'll have a fix for this in my next PR.

**Closed** 2022-10-31 13:36 UTC
