### ISSUE TITLE
App Fails to Start Due to Missing Module

### ISSUE THREAD

**Issue by jdrew82** [nautobot/nautobot-plugin-ssot-arista-cloudvision#77] opened 2022-07-27 13:56 UTC
### Environment
* Python version:  3.9
* Nautobot version:  1.3.8
* aristacv-sync version:  1.0.6

### Expected Behavior
Nautobot starts without issue and the plugin is available for use.

### Observed Behavior
Stacktrace is caused by a missing module:

```
Traceback (most recent call last):
  File "/usr/local/bin/nautobot-server", line 8, in <module>
    sys.exit(main())
  File "/usr/local/lib/python3.9/site-packages/nautobot/core/cli.py", line 54, in main
    run_app(
  File "/usr/local/lib/python3.9/site-packages/nautobot/core/runner/runner.py", line 266, in run_app
    management.execute_from_command_line([runner_name, command] + command_args)
  File "/usr/local/lib/python3.9/site-packages/django/core/management/__init__.py", line 419, in execute_from_command_line
    utility.execute()
  File "/usr/local/lib/python3.9/site-packages/django/core/management/__init__.py", line 395, in execute
    django.setup()
  File "/usr/local/lib/python3.9/site-packages/django/__init__.py", line 24, in setup
    apps.populate(settings.INSTALLED_APPS)
  File "/usr/local/lib/python3.9/site-packages/django/apps/registry.py", line 122, in populate
    app_config.ready()
  File "/usr/local/lib/python3.9/site-packages/nautobot_ssot_aristacv/__init__.py", line 34, in ready
    super().ready()
  File "/usr/local/lib/python3.9/site-packages/nautobot/extras/plugins/__init__.py", line 143, in ready
    jobs = import_object(f"{self.__module__}.{self.jobs}")
  File "/usr/local/lib/python3.9/site-packages/nautobot/extras/plugins/utils.py", line 45, in import_object
    spec.loader.exec_module(module)
  File "<frozen importlib._bootstrap_external>", line 850, in exec_module
  File "<frozen importlib._bootstrap>", line 228, in _call_with_frames_removed
  File "/usr/local/lib/python3.9/site-packages/nautobot_ssot_aristacv/jobs.py", line 15, in <module>
    from nautobot_ssot_aristacv.diffsync.tocv.cloudvision import CloudVision
  File "/usr/local/lib/python3.9/site-packages/nautobot_ssot_aristacv/diffsync/tocv/cloudvision.py", line 4, in <module>
    import nautobot_ssot_aristacv.diffsync.cvutils as cvutils
  File "/usr/local/lib/python3.9/site-packages/nautobot_ssot_aristacv/diffsync/cvutils.py", line 6, in <module>
    import arista.inventory.v1 as inv
  File "/usr/local/lib/python3.9/site-packages/arista/inventory/v1/__init__.py", line 3, in <module>
    from arista.inventory.v1 import inventory_pb2 as models
  File "/usr/local/lib/python3.9/site-packages/arista/inventory/v1/inventory_pb2.py", line 17, in <module>
    from fmp import extensions_pb2 as fmp_dot_extensions__pb2
  File "/usr/local/lib/python3.9/site-packages/fmp/__init__.py", line 3, in <module>
    import wrappers_pb2 as wrappers
ModuleNotFoundError: No module named 'wrappers_pb2'
```

### Steps to Reproduce
1. Build Nautobot
2. Add Arista CV SSoT plugin to environment and enable in PLUGINS.
3. Attempt to start Nautobot.

**Comment by jdrew82** [comment] 2022-07-27 15:05
This has been determined to be an issue within the cloudvision-python package and their imports. The project structure is wrong and there formats aren't using the project root in the path. This is allowing for the actual fmp project which was created in Apr 2022 to conflict and thus cause the error. This needs to be fixed in the cloudvision-python package. Ref https://github.com/aristanetworks/cloudvision-python/issues/7

**Comment by cianmcgrath** [comment] 2022-07-27 15:15
What version of the package is installed?
I believe that this issue was resolved in this [change](https://github.com/aristanetworks/cloudvision-python/commit/e932b200244a6591bf84bcf0d8ae31f63eeb35ec), so updating to v.1.4.3+ should resolve this

**Comment by jdrew82** [comment] 2022-07-27 15:33
This was using the latest version of cloudvision-python. I've specifically pointed out the issue in your project @cianmcgrath. You need to update your imports in your project to include the project name. Otherwise, you're allowing for other public packages like the fmp one to override. It is very obvious when you look at the file paths and the import statements.

**Comment by cianmcgrath** [comment] 2022-07-27 15:56
It's not up to date though
`import wrappers_pb2 as wrappers` is only in version 1.4.2 or before as the change I linked (which is a part of v1.4.3+) has `import fmp.wrappers_pb2 as wrappers` (which we have confirmed does work) and the fmp package on pypi does not have any contents in it's init.py file 

This is of course separate to your concern regarding the fmp package as a whole, which I've raised with the relevant teams

**Comment by jdrew82** [comment] 2022-07-27 16:12
Poetry specifically is picking 1.5.0 for some reason which is a bit strange since I see that has been yanked from PyPI. I've pinned it to 1.4.4 and tested it. It does appear that the issue is resolved with your tweak to fmp __init__.py file. I still think you should fix your imports to be more explicit and avoid this in the future. Probably need to figure out why 1.5.0 is still being pinned by Poetry too.

**Comment by cianmcgrath** [comment] 2022-07-28 15:06
Yes we are actively trying to resolve the imports issue you've raised and work our way forward with something more stable/less prone to package name collisions. It requires coordination between several internal teams though as there are a number of layers of automation involved in the release pipeline, so there might be a satisfactory resolution in the short term, but we are working on it.
1.5.0 also had to be yanked earlier on due to an issue with the release pipeline, so it is equivalent to 1.4.2 I think. 1.4.3+ have features/fixes not incorporated, including for the issue here
Apologies for interference with your your projects anyways, and thanks for raising the problem

**Comment by jdrew82** [comment] 2022-07-28 15:08
@cianmcgrath No worries. Appreciate you working with me to find a resolution and fix it going forward. We appreciate the work Arista has done in creating the library to assist us in creating this app.

**Closed** 2022-08-10 21:33 UTC
